### ISSUE TITLE
Analog audio output

### ISSUE THREAD

**Issue by NeosStore** [kszaq/OpenELEC.tv#10]
My MXQ through the non supplied aux cord isn't coming through my sound system, do i have to use the pre given cord for this to work or this an issue currently with the ROM ?

**Comment by kszaq** [comment]
Currently AV audio output doesn't work with OpenELEC and I can't promise I'll make it work.

**Comment by NeosStore** [comment]
Any Bypass ? to actually make it work ?

**Comment by jekkos** [comment]
Is SPDIF working?

**Comment by jekkos** [comment]
Any idea what exactly needs to be done to make this work? Isn't that code included in the amlogic kernel? Or does Kodi need to be modified to take advantage of it? Maybe I can try to help out as I'd like to use it as well.

**Comment by NeosStore** [comment]
Can't use SPDIF, dont have any thing supporting spdif

**Comment by jekkos** [comment]
Any idea if there's a pach around to make this happen? I did find something that enabled cvbs output in Kodi 

https://github.com/OpenELEC/OpenELEC.tv/issues/4502

Not sure if it allows simultaneous audio output next to the video.

**Comment by kszaq** [comment]
Analog audio output has been added in 6.0.1.2.

**Comment by jekkos** [comment]
whoa this is cool, cant wait to give that a whirl. Thanks for the good work!
