### ISSUE TITLE
Ignore HDMI CEC on init

### ISSUE THREAD

**Issue by TheVise** [kszaq/OpenELEC.tv#11]
Actually, when the MxQ starts up, it wakes up the TV and steals the input.

There is a way to ignore the HDMI CEC on init ? 

Thanks

**Comment by kszaq** [comment]
This requires modifying both u-boot and kernel.

**Comment by TheVise** [comment]
You'll be so kind enough to include it in the next release? :)

**Comment by kszaq** [comment]
Actually this is an intended behaviour and that's what many devices do. I will check if there's a way to send a power on command without "stealing" input but no promises.

**Comment by TheVise** [comment]
Let's keep our fingers crossed :+1:

**Comment by kszaq** [comment]
Update to 6.0.1.2 and following should help:
* boot into Android
* enter CEC config and disable One Touch Play
