### ISSUE TITLE
Remote 0x40 NEC and Vission 0x51

### ISSUE THREAD

**Issue by alpha-it** [kszaq/OpenELEC.tv#13]
I have two boxes. A remote control with NEC and the other with Visson S82. Both I have flashed with HD18Q and for testing with MXQ. With HD18Q everything is going well. Thank you! In the box with the Visson S82 remote I made the right remote.conf copied into the config directory. Control works. I can not start using the remote control this box, however. Both boxes I start with the NEC remote control. When NEC POWER is (116) ircode 0x40 and 0x51 = Visson S82. Where can I make this adjustment? I would compile it yourself.

(translated with Google Translate from German)

**Comment by kszaq** [comment]
I assume that you flashed the box with 6.0.0.1 or earlier? A power-on IR code is embedded in bootloader (example: https://github.com/kszaq/u-boot/commit/0dd20d8a839e8deec0dc2def580fc9b3aaeb7ad6#diff-4191ec5e94143f5f7080c45c6fbff414L4). The simplest way to fix it is flashing factory bootloader by re-flashing Android and then my OpenELEC release >=6.0.0.2.

**Comment by alpha-it** [comment]
Is there an alternative solution? Have both flashed on NAND :(

**Comment by kszaq** [comment]
Yes. If you have Android firmware and don't want to lose your data, you can create bootloader update ZIP by taking _bootloader.img_  from Android firmware and replacing it in one of these ZIPs: http://s805.eu/releases/6.0.0.1/Bootloader/ , resigning the zip and flashing it in recovery.

Alternatively, you can download u-boot source code, replace power on IR code (see commit referenced above) and compile it. You can find toolchain here: https://github.com/osmc/vero2-toolchain

**Comment by alpha-it** [comment]
Thanks! I flashed your old MXQ image and update to HD18Q 6.0.0.2. It works!
