### ISSUE TITLE
Add new wifi/BT module driver

### ISSUE THREAD

**Issue by bahrod** [kszaq/OpenELEC.tv#14]
Is it possible to add this wifi/BT module driver: AP6112?
Or how to add if get the driver source?

**Comment by kszaq** [comment]
Could you provide a reference on where it is used? Haven't seen that one before.

**Comment by bahrod** [comment]
Now, i use a MK808B plus TV stick with this wifi/BT module, sorry i make a mistake. Specs is AP6212

**Comment by kszaq** [comment]
AP6212 support has been added a long time ago: https://github.com/kszaq/OpenELEC.tv/releases/tag/5.0.8p16
