### ISSUE TITLE
Realtek RTL8189etv

### ISSUE THREAD

**Issue by tdodgy** [kszaq/OpenELEC.tv#15]
Please can you add support for this network card? It comes on some of the latest MXQs. The boards in question have HD180_V14 2015/12/21 imprinted. 

OpenELEC-Amlogic.HD18Q.arm-6.0.0.2 - does not detect wifi, remote works

OpenELEC-Amlogic.MXQ.arm-6.0.0.2 - detects wifi and connects but does not work, remote does not work

Thanks in advance!

**Comment by kszaq** [comment]
This is scheduled for the next release. I'll upload it in a few days, maybe today.

**Comment by tdodgy** [comment]
Thank you so much! I just checked some of the other open issues. I too have the one where the blue led is always on.

Will it be useful if I let you know the GPIOs with stock firmware?

**Comment by kszaq** [comment]
Actually I think I'll drop setting LEDs for HD18Q and leave LED management to uBoot. There are so many boards on the market, every one with different GPIO port for red/blue LED that I'm unable to support them all.

**Comment by tdodgy** [comment]
Ok great. I'm happy to test any pre-releases that support Realtek RT8189etv, please let me know...

**Comment by tdodgy** [comment]
The new release 6.0.1.1 works great with the Realtek RTL8189etv. Your efforts are truly appreciated.

Thanks again Kszaq.

**Comment by tdodgy** [comment]
Hi Kszaq

Just to let you know, your latest builds 6.95.1.x do eventually work this driver, although on initial connect, there are several error messages such as 'Invalid Arguments'. 

Thanks again for your work!

**Comment by kszaq** [comment]
I do not understand what the issue is. I don't have a device with RTL8189ETV to test it. Can you explain more? Provide logs?
