### ISSUE TITLE
Bluetooth audio

### ISSUE THREAD

**Issue by Milite777** [kszaq/OpenELEC.tv#16]
Is there any way to include bluetooth audio redirection in the next compiled version? Bluetooth working fine with any device, except with any bluetooth audio device (for example headphones). I've read that openelec doesn't natively support this fuction, but developer could include the correct driver in kernel.

**Comment by kszaq** [comment]
As far as I know, Bluetooth audio support has been added to OpenELEC 7.0. I'm not planning to add it to 6.0.x releases.

**Comment by kszaq** [comment]
Bluetooth audio works in 6.90.2.
