### ISSUE TITLE
OpenELEC-amlogic.MXQ.arm-6.0.1.1 remote.conf problem

### ISSUE THREAD

**Issue by scenicguy** [kszaq/OpenELEC.tv#17]
Hi Kszaq, my apologies for posting this in the wrong place. I have looked at so many forums over the last few days, that I got confused. I have flashed the OpenELEC-amlogic.MXQ.arm-6.0.1.1 to my MXQ-S805 v1.2 (HD18O v1.2) box and all is working fine, except for the remote which only partially works. I have tried to ssh a stock remote.conf using winscp but this always fails with an error 4 failure message. I cannot edit the file in winscp either. I am not familiar with PuTTy's commands and have no idea how to get the file from my windows pc into Openelec, any help would be very much appreciated as I am very happy with Openelec, which is considerably faster than Android and way smoother.

**Comment by kszaq** [comment]
First of all, you should try HD18Q build as it has different _remote.conf_ that may work with your remote.

If you want to push your own configuration file, you can put it in _Configuration_ folder of Samba share (\\OpenELEC\Configuration in Windows). This is covered in FAQ. You can't write to System partition as it is a read-only SquashFS file system.

**Comment by scenicguy** [comment]
Ok, will give that a try. Thanks so much for your help.

Sent from my Sony Xperia™ smartphone

---- kszaq wrote ----

**Comment by scenicguy** [comment]
Thanks again kszaq, I installed the HD18Q build and the remote is working perfectly.

I now only have one issue concerning the pvr iptv simple client needed for Live TV with Dexter Pro TV. Although I can install the client from the Openelec (official) repository, it disables itself as soon as I back out from configuring it. Any ideas how I can get either this client or another to configure with Dexter Tv Pro and let me watch live tv?

As always, any advice would be most appreciated and congratulations on such an excellent build.

**Comment by jbmediabox** [comment]
Hi Kszaq:

I am sorry if I am repeating this question but I flashed my MXv S805 with your OpenELEC-Amlogic.MXQ.arm-6.0.1.1 and it works fine except my IR remote doesn't work at all. Can you please assist ? do i need to copy the remote.config file somewhere and how

Really appreciate

JB

**Comment by kszaq** [comment]
One of these should work:
https://raw.githubusercontent.com/kszaq/OpenELEC.tv/openelec-6.0-rebase/projects/Amlogic/devices/HD18Q/filesystem/etc/amremote/remote.conf
https://raw.githubusercontent.com/kszaq/OpenELEC.tv/openelec-6.0-rebase/projects/Amlogic/devices/MXQ/filesystem/etc/amremote/remote.conf

Copy one of them directly to Configfiles folder:
http://wiki.openelec.tv/index.php/Accessing_Samba_Shares

**Comment by ArjenD** [comment]
i tried both the remote.conf files, but both do not work on a **MXV**. any other ideas?

**Comment by kszaq** [comment]
@ArjenD, have you tried extracting _remote.conf_ from your Android ROM? Also remember to reboot after uploading the file or restart amremote service over SSH.

**Comment by ArjenD** [comment]
i copied the original _remote.conf_ from the original rom, but just will not work. 
Is it possible to see some logging of this file loading? how do i restart de amremote service ??

**Comment by kszaq** [comment]
@ArjenD If you want to reload amlogic service, use `systemctl restart amlogic-remotecfg.service` command. You can also run `remotecfg _path_to_your_config_file_` to load a custom file to test it. Loading progress can be seen in dmesg and with second command also in console.

**Comment by ArjenD** [comment]
ok, thanks for the info
