### ISSUE TITLE
OpenELEC-Amlogic.HD18Q.arm-6.0.1.4.zip

### ISSUE THREAD

**Issue by fannyfaz** [kszaq/OpenELEC.tv#18]
Hi kszaq

I've just tried to instal the above image to my MXW HD180Q_V1.0 board it instals fine but when it goes to reboot it just gets stuck in a rebooting loop 

I've have tried the other versions and they work great but have no remote and no wifi i can fix the remote but cant get the wifi working 

Can i change the bootloader from one of the other releases into the OpenELEC-Amlogic.HD18Q.arm-6.0.1.4.zip one???

if so is there any tutorials on how to do it?

Thanks

**Comment by kszaq** [comment]
My releases don't replace bootloader.

**Comment by fannyfaz** [comment]
ok thanks is there a way i can add the wifi driver from the rom that i have this is a ljnk to the rom
http://www.vtzero.com/download/TV_BOX/MXQ_Original/hd18q_ota_20151222.rar

**Comment by kszaq** [comment]
No, you have to compile the ROM to modify WiFi drivers. The WiFi drivers are exactly the same in all my releases. In your case non-working WiFi is a matter of device tree and not drivers.

**Comment by fannyfaz** [comment]
ok thats more than i know how to do any tutorials you know of how i can try and learn that?

thanks for your help

**Comment by kszaq** [comment]
You have to replace device tree with a one that works, e.g. from Android firmware. Start with http://www.cnx-software.com/2014/05/12/how-to-extract-a-device-tree-file-from-android-firmware-files/ and MXQ 6.0.1.4 release.

**Comment by fannyfaz** [comment]
ok that is well past my ability shame guess i'll have to wait for someone else to show me a working openelec for the HD180Q\_V1.0 board 

thanks for you help

**Comment by kszaq** [comment]
Honestly I wouldn't count on that - too many boards on the market to support them all.

**Comment by fannyfaz** [comment]
yeah that's what i thought the answer was going to be

**Comment by kszaq** [comment]
Sorry for that. I am unable to compile reliably working builds for boards I don't have.
