### ISSUE TITLE
MK808B Plus hang on boot logo

### ISSUE THREAD

**Issue by piotrekcrash** [kszaq/OpenELEC.tv#19]
Sometimes when I turn off TV without previously close OpenELEC from menu (stick powered from USB in TV), next boot is finish on Boot logo always. Then I need to factory reset from Recovery to fix it.
Is this known issue? Is there a way to safe turn of device by cut the power or only menu option is safe?

**Comment by kszaq** [comment]
Which version do you use?

**Comment by piotrekcrash** [comment]
Currently 6.0.3.1 (my device is clone with rtl8723)

**Comment by kszaq** [comment]
When you cut the power, _profiles.xml_ might get corrupted and that causes Kodi not to load. Fix for this is present in 6.0.3.4. Please upgrade to 6.0.3.4 or to [6.0.3.5 test build](http://s805.eu/test/6.0.3.5-build1/).

**Comment by piotrekcrash** [comment]
I updated to 6.0.3.4 and tested many times. Now seems to be ok. Many thanks!
