### ISSUE TITLE
CEC stop working after some time.

### ISSUE THREAD

**Issue by piotrekcrash** [kszaq/OpenELEC.tv#20]
I have two MK808B Plus (both clones)

One is working perfect with CEC and one have some issue. After some time (sometimes few seconds, sometimes few minutes) TV stop recognising device as CEC supported. After restart everthing is ok for next short time. Reset CEC on TV also sometimes help.
Very diffucult in case of two identical device is that one work perfect and one not.
(Both runned 6.0.3.1 and works different, ow tested also with 6.0.3.4, problem still apear)
I think this is not problem with Your firmware but maybe You have idea what can be wrong.

**Comment by kszaq** [comment]
Please check the devices using the same cable. If it doesn't work with only one of them, this may be a hardware issue.

**Comment by piotrekcrash** [comment]
I checked on the same cable and nothing changed. I'll buy new one. You can close this issue but maybe You can reccommend if better is to buy some clone or original Tronsmart device MK808B Plus device? Thanks

**Comment by kszaq** [comment]
My MK808B+ is more than 1 year old and I don't think you'll be able to get the exact same device so I won't give recommendations. Before you buy a new device, you can try re-flashing stock firmware as sometimes bootloader can interfere in how CEC works.

**Comment by piotrekcrash** [comment]
Today I flashed device with newest Tronsmart firmware 112k4 and then Your OpenELEC.
I'm testing almost one hour and works fine! Many thanks for this advice.
Tomorrow I'll do more test and inform here but previously CEC stopped work after few minutes so it seems to be fixed.

**Comment by kszaq** [comment]
That's good to hear. :) If you think your issue is resolved, please close this request.
