### ISSUE TITLE
Audio passthrough via optical S/PDIF

### ISSUE THREAD

**Issue by sivanoff** [kszaq/OpenELEC.tv#22]
AC3 audio passthrough works in 6.0.3.5 on my S805 device CS918G PLUS. But somehow it doesn't work in 6.95.1.1 - no sound output with same settings as in 6.0.3.5.
I want my bluetooth headset working, but I want 5.1 audio too.

Can we do something to make optical output work in 6.95.1.1 same way as in 6.0.3.5?

**Comment by kszaq** [comment]
There is no difference in how passthrough works between 6.0.3.5 and 6.95.1.1. It works for me... Have you tried both builds: MXQ and HD18Q?

**Comment by sivanoff** [comment]
Yes, tried HD18Q, same results - no sound in passthrough mode. Maybe they broke something while adding bluetooth sound output.
Meanwhile managed to get 5.1 sound back connecting external usb sound card.

**Comment by kszaq** [comment]
Can you confirm once again that passthrough works for you in 6.0.3.5?

**Comment by sivanoff** [comment]
Yes, I can confirm optical S/PDIF outputs dolby digital when I run OE 6.0.3.5.

**Comment by kszaq** [comment]
With 6.95.1.1, can you try if you get audio doing this:
* play AC3 audio track with passthrough enabled
* while playing, execute `echo 2 > /sys/class/audiodsp/digital_codec`

**Comment by sivanoff** [comment]
Thanks, it outputs AC3 after I executed this command. But now I hear no sound with regular stereo.

**Comment by kszaq** [comment]
Thank you for your report. I will re-include a patch that switches this automatically for a next release.

**Comment by kszaq** [comment]
This should be fixed in latest version.
