### ISSUE TITLE
building nand image

### ISSUE THREAD

**Issue by lavvy** [kszaq/OpenELEC.tv#24]
hi kszaq , how do i build this repo for hd18q nand image. i tried this and ended with error .
please could you help me with steps to build for hd18q nand image
see what i did .

  PROJECT=Amlogic ARCH=arm DEVICE=HD18Q make image

building on ubuntu 14.04 , after about an hour it terminated with errors

**Comment by kszaq** [comment]
What error do you get?

**Comment by lavvy** [comment]
i think it started here


/home/ubuntu/OpenELEC.tv/build.OpenELEC-Amlogic.arm-6.95.1.1/toolchain/bin/host-gcc -m32 -I../lib  -O2 -Wall -pipe -I/home/ubuntu/OpenELEC.tv/build.OpenELEC-Amlogic.arm-6.95.1.1/toolchain/include -Wno-format-security -Wl,-rpath,/home/ubuntu/OpenELEC.tv/build.OpenELEC-Amlogic.arm-6.95.1.1/toolchain/lib -L/home/ubuntu/OpenELEC.tv/build.OpenELEC-Amlogic.arm-6.95.1.1/toolchain/lib -DENABLE_LZ4C_LEGACY_OPTIONS ../lib/lz4.c ../lib/lz4hc.c ../lib/lz4frame.c ../lib/xxhash.c bench.c lz4io.c lz4cli.c -o lz4c32
In file included from /usr/include/stdlib.h:24:0,
                 from ../lib/lz4.c:105:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
In file included from /usr/include/stdlib.h:24:0,
                 from ../lib/lz4.c:105,
                 from ../lib/lz4hc.c:65:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
In file included from /usr/include/stdlib.h:24:0,
                 from ../lib/lz4frame.c:52:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
In file included from /usr/include/stdlib.h:24:0,
                 from ../lib/xxhash.c:90:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
In file included from /usr/include/stdlib.h:24:0,
                 from bench.c:47:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
In file included from /usr/include/stdio.h:27:0,
                 from lz4io.c:49:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
In file included from /usr/include/stdio.h:27:0,
                 from lz4cli.c:58:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
Makefile:82: recipe for target 'lz4c32' failed
make[2]: *** [lz4c32] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/ubuntu/OpenELEC.tv/build.OpenELEC-Amlogic.arm-6.95.1.1/lz4-r131/programs'
Makefile:66: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/OpenELEC.tv/build.OpenELEC-Amlogic.arm-6.95.1.1/lz4-r131'
make: *** [image] Error 2

**Comment by kszaq** [comment]
Please read http://askubuntu.com/questions/470796/fatal-error-sys-cdefs-h-no-such-file-or-directory and comments to https://github.com/OpenELEC/OpenELEC.tv/pull/4289 I hope you can find a solution there.

**Comment by lavvy** [comment]
thanks @kszaq
