### ISSUE TITLE
Can't flash the compiled version. Signature verification failed

### ISSUE THREAD

**Issue by felixdreinulldrei** [kszaq/OpenELEC.tv#25]
Hi,

I'm able to build your Version of OpenELEC successfully, but not able to flash
the compiled files. Verification failure.

Build with
PROJECT=Amlogic DEVICE=MXQ ARCH=arm make release

At the end of the compilation I have 3 files in the target folder 

OpenELEC-Amlogic.MXQ.arm-6.95.1.3.kernel
OpenELEC-Amlogic.MXQ.arm-6.95.1.3.system
OpenELEC-Amlogic.MXQ.arm-6.95.1.3.tar 

What I did was to replace kernel and system files from your OpenELEC NAND Release,
with the one I have build. To do this I just unzipped your OpenELEC-Amlogic.MXQ.arm-6.95.1.3-update.zip
and copied my builds in the corresponding folders. 

zipped the folder again with in terminal with 
[zip -r9 OpenELEC-Amlogic.MXQ.arm-6.95.1.3-update-unsigned.zip OpenELEC-Amlogic.MXQ.arm-6.95.1.3-update ]

signed with tools from your repo.
[java -jar signapk.jar testkey.x509.pem  testkey.pk8 OpenELEC-Amlogic.MXQ.arm-6.95.1.3-update-unsigned.zip OpenELEC-Amlogic.MXQ.arm-6.95.1.3-update.zip]

At the end I copied 

aml_autoscript
factory_update_param.aml
OpenELEC-Amlogic.MXQ.arm-6.95.1.3-update.zip
recovery.img

to the sd card and started to flash with toothpick method.
but I'm getting this errors

Finding update package…
Opening update package…
E:footer is wrong
E: signature verification failed
Installation aborted
Formatting /data
Formatting /cache
Data wipe failed…
Cache wipe failed.

When I flash your original files there is no problem.
But I would like to flash the one I have compiled :)

Is there anything i missed to do?
Any help to solve this?

**Comment by kszaq** [comment]
Use **make amlpkg** to build update ZIP for NAND installation or **make image** to build both SD card and NAND image.
