### ISSUE TITLE
MK808B+ Says Bluetooth Adapter not Found

### ISSUE THREAD

**Issue by jasmas** [kszaq/OpenELEC.tv#27]
Possibly related to the patch below?
https://github.com/arco/linux-amlogic/commit/c7c50ac0c3b840b57ee5bdee8779a5c86234b09a

**Comment by kszaq** [comment]
This patch is already included. What is your WiFi/BT chip? Bluetooth in Realtek 8723BS is not supported.

**Comment by jasmas** [comment]
Best way to check?

**Comment by kszaq** [comment]
`lsmod` in terminal.

**Comment by jasmas** [comment]
It appears it is unsupported.

**Comment by sivanoff** [comment]
Maybe we can do something to make bluetooth supported for 8723BS? Under android its supported.

**Comment by kszaq** [comment]
I don't have a device with 8723bs to test.

**Comment by kszaq** [comment]
For Realtek 8723BS Bluetooth you can try this test build: http://sx05.eu/test/le_8723bs_bt_test_01/

**Comment by sivanoff** [comment]
Can't find info on how to boot this test build from sdcard.

**Comment by sivanoff** [comment]
Thanks, bluetooth controller now visible. This patch enables bt support https://github.com/kszaq/linux/commit/8696206ae5d97c1263b1d2ede595a0d629019742
?
