### ISSUE TITLE
acestream and retroarch

### ISSUE THREAD

**Issue by zippy165141** [kszaq/OpenELEC.tv#29]
hi do you know why i cant get theses working? i will be happy to paid for help on getting these working

**Comment by kszaq** [comment]
For retroarch, follow this guide:
http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/s805/others-ab/561477-retroarch-addon-for-openelec-on-mk808b-and-mxq

For Acestream (and any other plugin) you have to provide OE logs and ask on forums, 3rd party plugins are not supported by me.
