### ISSUE TITLE
IR Remote Not Working

### ISSUE THREAD

**Issue by RozebMomin** [kszaq/OpenELEC.tv#37]
I have an MXQ device with the IR Remote and I used the 6.0.3.8 System and I am lost on how to proceed further to get my remote working again.

**Comment by kszaq** [comment]
Have you resolved your issue?

**Comment by RozebMomin** [comment]
Yes I have. I had to extract the remote.conf and replace it with the one for my remote. Thank you very much for your work!

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.6.23&pv=9.2.1&source=email_footer_2]
On Thu, Jun 2, 2016 at 2:20 AM, kszaq <notifications@github.com> wrote:
Have you resolved your issue?
