### ISSUE TITLE
wget: unable to resolve host address 's805.eu'

### ISSUE THREAD

**Issue by lavvy** [kszaq/OpenELEC.tv#38]
Cant't get linux sources : http://s805.eu/sources/linux-amlogic-3.10-cf51189.tar.xz
 Try later !!
make: *** [image] Error 1

please how do i resolve this error. i had been compiling this fork a long time , but this time its strange. i had waited for about 10 hrs, yet its still not going

**Comment by kszaq** [comment]
Please update your local repository, URL has changes a few weeks ago: https://github.com/kszaq/OpenELEC.tv/commit/5095f2f0a68fabdd62fd40c94fa1f221443eaa64
