### ISSUE TITLE
Reinstall android? I have no recovery

### ISSUE THREAD

**Issue by pikomule** [kszaq/OpenELEC.tv#4]
I tried to install firmware Stock, finless, etc with the method of RESET, but does nothing, just start OpenELEC?

How can I restore RECOVERY?

Neither works by connecting the PC to use USB Burning Tool

Thanks

**Comment by kszaq** [comment]
Prepare SD card with Android firmware image - you need to have *recovery.img*, *aml_autoscript* and firmware image, then issue `reboot recovery` command in OpenELEC.

**Comment by pikomule** [comment]
I found the problem, the reset button was not good soldier.

Thanks
