### ISSUE TITLE
Disable HDMI-CEC

### ISSUE THREAD

**Issue by techetga** [kszaq/OpenELEC.tv#7]
Is there any way I can disable HDMI-CEC entirely? It's a pain when my TV keeps switching to the HDMI channel. I can't disable HDMI-CEC in the TV.

**Comment by oCanna** [comment]
You could disable cec at startup:
echo 0 > /sys/devices/virtual/amhdmitx/amhdmitx0/cec_config

But this probably won't prevent ur TV from switching to the HDMI channel on boot. I guess you need to change the default linux commandline parameter from "hdmitx=cecf" to "hdmitx=cec0" and rebuild the image.

**Comment by techetga** [comment]
The first didn't work, and I don't know how to do the second. Thanks anyway :)

**Comment by kszaq** [comment]
@techetga you can try using this addon: http://openelec.tv/forum/146-wetek-play/78681-wetek-hdmi-cec-enabler-add-on

I don't know if it offers turning off CEC but you can try.

**Comment by kszaq** [comment]
In 6.0.1.2 you can disable CEC in Android and it'll also disable CEC in OpenELEC.
