### ISSUE TITLE
"Reboot from NAND" menu option not working on MK808b plus

### ISSUE THREAD

**Issue by shamanNS** [kszaq/OpenELEC.tv#8]
"Reboot from NAND" option in Kodi's power/reboot menu is not working on MK808b plus. OpenELEC v5.95.5.2. 
Nothing happens when I click, menu closes and that is it, it just sits there on Kodi home screen.

**Comment by kszaq** [comment]
Thank you for reporting that. I missed some files from *packages* folder when moving changes between branches. This will be fixed in next release.

**Comment by shamanNS** [comment]
yeah, I noticed that it's missing the .sh file in /usr/bin or wherever that is referenced in .xml file for Kodi's reboot menu. The "reboot switch_system" command over SSH works, so I've been using that to avoid having to eject the SD card.

**Comment by kszaq** [comment]
For future versions I will not replace bootloader and make a small modification to uenv instead. This would prevent users from unintentionally flashing wrong bootloader (and bricking a device) but there would be no way to tell the bootloader to boot from NAND and I'll be removing "Reboot from NAND" option from my ROM. You can stay with old bootloader and keep *reboot switch_system* option working.

**Comment by kszaq** [comment]
"Reboot from NAND" is back in 6.0.3.5/6.95.1.1.
